# Generated by Django 3.1.4 on 2021-01-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_auto_20210102_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birth',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
