# Generated by Django 3.1.4 on 2021-01-09 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0011_remove_customuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='finalEducation',
            field=models.CharField(choices=[('초등학교 졸업', '초등학교 졸업'), ('중학교 졸업', '중학교 졸업'), ('고등학교 졸업', '고등학교 졸업'), ('대학교 졸업', '대학교 졸업'), ('석사 졸업', '석사 졸업'), ('박사 졸업', '박사 졸업')], default='', max_length=15, null=True),
        ),
    ]
